### ISSUE TITLE
Random VDC is shown, vdc_id query param is ignored

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/G8VDC#12]
On the WHMCS/Moehaha Docker container we've created following **test.html**:
```
<head>
yves-macbook-pros-MacBook-Pro:~ yves$
    <title>Title</title>
    <script src="https://moehaha.com/templates/fusion/g8vdc/vdccontrol.js"></script>
</head>
<body>
<iframe id="vdc" src="templates/fusion/g8vdc/index.html" style="position: absolute; height: 100%; border: none" height="100%" width="100%"></iframe>
</body>
</html>
```

When using it as shown below **VDC with ID 16** is shown, while **VDC with ID 27** is expected/requested:

https://moehaha.com/test.html?jwt=eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXJ0aWxpdW12MiJdLCJleHAiOjE0NzcwNjI5NDEsImlzcyI6Iml0c3lvdW9ubGluZSIsInNjb3BlIjoidXNlcjpuYW1lIiwidXNlcm5hbWUiOiJqZGVscnVlIn0.AW5UY1G1zot6ZQ40BWpfV0ikMWo2BA3FSLVcIBzJ511Ii8YJyBE9ccjF2QnP7CI_GdTodu5689IYfCuAvGAK01dNzvelScdRI--0K2hgJvznakzmqDznE4VvaWWekYGN&vdc_id=27&g8_domain=ma-g8-1.demo.greenitglobe.com

If you need access to the Docker container, please contact me

**Comment by grimpy** [comment]
Fixed on master
