### ISSUE TITLE
Usage documentation on how to integrate the VDC Control.

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/G8VDC#2]
This repository lacks documentation on how to integrate it in a website.

**Comment by grimpy** [comment]
@yveskerwyn could you add a readme that points to the gitbook?

**Comment by yveskerwyn** [comment]
@grimpy [README](https://github.com/0-complexity/G8VDC/blob/master/README.md) was already pointing to [VDC Control Panel GitBook](https://gig.gitbooks.io/g8-vdc-control-panel/content/)
