### ISSUE TITLE
Console doesn't show when used in the Artilium e-portal

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/G8VDC#28]
Needs investigation, please contact me when available

![screen shot 2017-03-07 at 18 33 27](https://cloud.githubusercontent.com/assets/13795109/23669493/a5bb455e-0364-11e7-9870-769e95a0ccb1.png)

**Comment by hofkensj** [comment]
![image](https://cloud.githubusercontent.com/assets/16613288/23790206/7dea2312-057e-11e7-968e-ffb1ca5ec3d0.png)

**Comment by hofkensj** [comment]
see error messages on the right

**Comment by grimpy** [comment]
was vpn opened during this session? be-scale-1 is behind vpn

**Comment by yveskerwyn** [comment]
Yes, but maybe not for the iframe... 

Is it possible that the iframe doesn't go through the VPN? Not sure whether that makes sense?

**Comment by grimpy** [comment]
it doesn not make sense for a public e portal to use an enviroment that is not publicly exposed.

**Comment by FastGeert** [comment]
problem is they run their portal on http
