### ISSUE TITLE
Internal error (500) when using VDC Control Panel

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/G8VDC#8]
When using the VDC Control Panel with a correct JWT and valid VDC ID we get an error

The whoami and list REST call return error 500, see screenshot

Bug or wrong usage?

![image](https://cloud.githubusercontent.com/assets/13795109/16805054/c7f60e6c-490e-11e6-901a-a0082cf19c72.png)

**Comment by grimpy** [comment]
@yveskerwyn can you still reproduce this?

**Comment by yveskerwyn** [comment]
Let's close it, they've got it working now
